# Generated by Django 5.0.6 on 2024-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0036_contactmodel_status_usercontactmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('dispatched', 'dispatched'), ('order-placed', 'order-placed'), ('delivered', 'delivered'), ('shipped', 'shipped'), ('cancelled', 'cancelled')], default='order-placed', max_length=100),
        ),
    ]
